#!/bin/sh

PIDFile=/tmp/pomodoro.pid
pomoFile=/tmp/pomodoro
interval=1500
winderTicks=12

cleanUp() {
    if [ -e $pomoFile ]; then
        rm $pomoFile
    fi
}

endPomo() {
    osascript -e 'display notification "ding" with title "🍅" sound name "default"'
    cleanUp
}

initPomo() {
    (sleep $interval; endPomo)&
    echo $! > $PIDFile
    echo "$(date '+%H:%M') -> $(date -v +${interval}S '+%H:%M')" > $pomoFile
}

stopPomo() {
    if [ -e $PIDFile ]; then
        pomoPID=$(cat $PIDFile)
        checkPID=$(pgrep -f "pomodoro start")
        if (echo "$checkPID" | fgrep --silent --word-regexp "$pomoPID"); then
            kill -TERM $pomoPID
        fi
        rm $PIDFile
    fi
    cleanUp
}

reportPomo() {
    if [ -e $pomoFile ]; then
        cat $pomoFile
    fi
}

windPomo() {
    inputCount=0
    prompt="Wind-up the timer: "
    while IFS= read -p "$prompt" -r -s -n 1 char; do
        inputCount=$(expr $inputCount + 1)

        if [ $inputCount -gt $winderTicks ] || [ $inputCount -eq $winderTicks ]; then
            break
        fi

        prompt="*"
    done
    echo
}

printUsage() {
    echo "Usage: pomodoro [wind|start|stop|status]"
    exit 1
}

startPomo() {
    stopPomo
    initPomo
    reportPomo
}

if [ "$1" = "start" ]; then
    startPomo
    exit
elif [ "$1" = "stop" ]; then
    stopPomo
    exit
elif [ "$1" = "status" ]; then
    reportPomo
    exit
elif [ "$1" = "wind" ]; then
    windPomo
    startPomo
    exit
fi

printUsage
